version: '2'
services:
  web:
    restart: always
    environment:
      TEST_DATA: "true"
    ports:
      - "80:8000"
  db:
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: {}
